Improved setup script

diff --git a/setup/papiex-oss.sh.in b/setup/papiex-oss.sh.in
--- a/setup/papiex-oss.sh.in
+++ b/setup/papiex-oss.sh.in
@@ -1,25 +1,29 @@
 called="${BASH_SOURCE[@]}"
-if [[ $called == $0 ]]; then
-  echo "You tried executing $0"
-  echo "Instead you need to source the script in your shell:"
-  echo "  source $0"
-  exit 1
+echo "Dollar0: ($0)"
+if [ "${called}" ] ; then
+    if [[ $called == $0 ]]; then
+	echo "Error: *source* this script, do not execute it"
+	exit 1
+    fi
+    echo "Called: (${called})"
+    dirto=$(dirname "${called}")
+    echo "Dirname $?: (${dirto})"
+else
+    dirto="`pwd`"
 fi
-echo "Called: (${called})"
-dirto=$(dirname "${called}")
-echo "Dirname: (${dirto})"
 
 case "${dirto}" in
-  /*)   echo "Yes slash found" ; 
+  /*)   #echo "Yes slash found"
 	;;
-  *)    echo "No slash found" ; 
-	mycwd=`pwd`; dirto="${mypwd}/${dirto}" ;;
+  *)    #echo "No slash found"; 
+	dirto="`pwd`/${dirto}" ;;
 esac
+#echo "Looking for (${dirto})"
 
 test -d "${dirto}" || echo "Error: ${dirto} does not exist."
 TOOLS_INSTALL_DIR="${dirto}"
 
-echo "Loading tools from ${TOOLS_INSTALL_DIR}"
+echo "Tools installed in ${TOOLS_INSTALL_DIR}. Modifying PATH/MANPATH/LD_LIBRARY_PATH env. vars."
 export PATH="$TOOLS_INSTALL_DIR/bin:$PATH"
 export MANPATH="$TOOLS_INSTALL_DIR/man:$TOOLS_INSTALL_DIR/share/man:$MANPATH"
 export LD_LIBRARY_PATH="$TOOLS_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
