Updated directory handling

diff --git a/setup/papiex-oss.sh.in b/setup/papiex-oss.sh.in
--- a/setup/papiex-oss.sh.in
+++ b/setup/papiex-oss.sh.in
@@ -3,19 +3,23 @@ if [[ $called == $0 ]]; then
   echo "You tried executing $0"
   echo "Instead you need to source the script in your shell:"
   echo "  source $0"
-    exit 1
+  exit 1
 fi
-dir=$(dirname $called)
+#echo "Called: (${called})"
+dirto=$(dirname "${called}")
+#echo "Dirname: (${dirto})"
 
-case "$dir" in
-  /*) ;;
-  *) dir="${PWD}/$dir"
+case "${dirto}" in
+  /*)   #echo "Yes slash found"
+	;;
+  *)    #echo "No slash found"; 
+	mycwd=`pwd`; dirto="${mypwd}/${dirto}" ;;
 esac
 
-test -d "$dir" || echo "Error: $dir does not exist."
-TOOLS_INSTALL_DIR="$dir"
+test -d "${dirto}" || echo "Error: ${dirto} does not exist."
+TOOLS_INSTALL_DIR="${dirto}"
 
-echo Loading tools from $TOOLS_INSTALL_DIR
+echo "Loading tools from ${TOOLS_INSTALL_DIR}"
 export PATH="$TOOLS_INSTALL_DIR/bin:$PATH"
 export MANPATH="$TOOLS_INSTALL_DIR/man:$TOOLS_INSTALL_DIR/share/man:$MANPATH"
 export LD_LIBRARY_PATH="$TOOLS_INSTALL_DIR/lib:$LD_LIBRARY_PATH"
