Update compile_and_test_papiex.yml

diff --git a/.github/workflows/compile_and_test_papiex.yml b/.github/workflows/compile_and_test_papiex.yml
--- a/.github/workflows/compile_and_test_papiex.yml
+++ b/.github/workflows/compile_and_test_papiex.yml
@@ -44,8 +44,12 @@ jobs:
         run: |          
           # Generate SSH host keys without a passphrase for testing purposes only.
           # This is acceptable in this controlled test environment as the image is not used in production.
+          ls ~/.ssh && echo ".ssh dir exists!" || echo ".ssh dir does not exist!"
+          mkdir ~/.ssh && echo ".ssh dir created!" || echo ".ssh dir could not be created but its OK!"          
           ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' 
-          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N "" && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
+          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N "" 
+          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys 
+          chmod 600 ~/.ssh/authorized_keys
 
       - name: configure csh user
         run: |
